import 'swiper/dist/css/swiper.css'
// import 'element-ui/lib/theme-chalk/index.css'
import './common.styl'
import './icon.styl'
import './reset.styl'
import './special.styl'
import './util.styl'
import './anime.styl'
import './page-common.styl'
import './el-reset.styl'
import './nav.styl'

import 'mint-ui/lib/style.css'
// import '../share/css/share.css'
